#!/usr/bin/env bash
# format-output.sh — Render verified findings as a markdown PR review.
#
# Usage: format-output.sh /tmp/pr-review-findings.json
#
# Input JSON shape (produced by the orchestrator after Phases 2-4):
#   {
#     "verdict": "LGTM | DISCUSS | NEEDS_CHANGES",
#     "pr": { "title", "url", "author", "additions", "deletions", "changed_files" },
#     "counts": { "critical": N, "major": N, "minor": N, "trivial": N, "info": N },
#     "agents_run": ["bugs", "security", ...],
#     "agents_failed": [],
#     "findings": [ {finding objects with verified:true|partial} ],
#     "unverified_suspicions": [ {findings rejected by verify} ]
#   }
#
# Output: a single markdown block on stdout.
set -euo pipefail

INPUT="${1:-}"
[[ -z "$INPUT" || ! -r "$INPUT" ]] && { echo "format-output.sh: missing or unreadable input: $INPUT" >&2; exit 2; }
command -v jq >/dev/null 2>&1 || { echo "format-output.sh: jq not found" >&2; exit 2; }

emoji_for_severity() {
  case "$1" in
    Critical) echo "🔴" ;;
    Major)    echo "🟠" ;;
    Minor)    echo "🟡" ;;
    Trivial)  echo "🔵" ;;
    Info)     echo "⚪" ;;
    *)        echo "•" ;;
  esac
}

emoji_for_type() {
  case "$1" in
    potential_issue) echo "⚠️" ;;
    refactor)        echo "🛠️" ;;
    nitpick)         echo "🧹" ;;
    *)               echo "•" ;;
  esac
}

emoji_for_verdict() {
  case "$1" in
    LGTM)          echo "✅" ;;
    DISCUSS)       echo "💬" ;;
    NEEDS_CHANGES) echo "🚫" ;;
    *)             echo "•" ;;
  esac
}

VERDICT=$(jq -r '.verdict' "$INPUT")
PR_TITLE=$(jq -r '.pr.title // "Untitled"' "$INPUT")
PR_URL=$(jq -r '.pr.url // ""' "$INPUT")
PR_AUTHOR=$(jq -r '.pr.author // "unknown"' "$INPUT")
PR_ADDS=$(jq -r '.pr.additions // 0' "$INPUT")
PR_DELS=$(jq -r '.pr.deletions // 0' "$INPUT")
PR_FILES=$(jq -r '.pr.changed_files // 0' "$INPUT")

C_CRIT=$(jq -r '.counts.critical // 0' "$INPUT")
C_MAJ=$(jq -r '.counts.major // 0' "$INPUT")
C_MIN=$(jq -r '.counts.minor // 0' "$INPUT")
C_TRIV=$(jq -r '.counts.trivial // 0' "$INPUT")
C_INFO=$(jq -r '.counts.info // 0' "$INPUT")

AGENTS_RUN=$(jq -r '.agents_run | join(", ")' "$INPUT")
AGENTS_FAILED=$(jq -r '.agents_failed | if length == 0 then "none" else join(", ") end' "$INPUT")

cat <<EOF
# $(emoji_for_verdict "$VERDICT") PR Review: $PR_TITLE

EOF

[[ -n "$PR_URL" ]] && echo "**PR**: $PR_URL"
echo "**Author**: $PR_AUTHOR  •  **Changes**: $PR_FILES files, +$PR_ADDS / -$PR_DELS"
echo ""
echo "**Verdict**: $(emoji_for_verdict "$VERDICT") **$VERDICT**"
echo ""
echo "## Summary"
echo ""
echo "| Severity | Count |"
echo "|---|---|"
echo "| 🔴 Critical | $C_CRIT |"
echo "| 🟠 Major | $C_MAJ |"
echo "| 🟡 Minor | $C_MIN |"
echo "| 🔵 Trivial | $C_TRIV |"
echo "| ⚪ Info | $C_INFO |"
echo ""
echo "**Agents run**: $AGENTS_RUN"
[[ "$AGENTS_FAILED" != "none" ]] && echo "**Agents failed**: $AGENTS_FAILED (confidence reduced)"
echo ""

# Findings grouped by severity
for sev in Critical Major Minor Trivial Info; do
  count=$(jq -r --arg s "$sev" '[.findings[] | select(.severity == $s)] | length' "$INPUT")
  [[ "$count" -eq 0 ]] && continue

  echo "## $(emoji_for_severity "$sev") $sev ($count)"
  echo ""

  jq -r --arg s "$sev" '
    .findings[] | select(.severity == $s) |
    "### \(if (.cwe // "") != "" then "[\(.cwe)] " else "" end)\(.title)\n" +
    "**File**: `\(.file):\(.line_start)\(if .line_end != .line_start then "-\(.line_end)" else "" end)`  •  " +
    "**Category**: `\(.category)`  •  **Type**: `\(.type)`\(if .verified == "partial" then "  •  ⚠️ _partial verification_" else "" end)\n\n" +
    "**Description**: \(.description)\n\n" +
    "**Impact**: \(.impact)\n\n" +
    "**Recommendation**: \(.recommendation)\n\n" +
    (if (.code_snippet // "") != "" then "```\n\(.code_snippet)\n```\n\n" else "" end) +
    (if (.receipts // "") != "" then "<details><summary>Receipts (\(.evidence_type))</summary>\n\n```\n\(.receipts)\n```\n</details>\n\n" else "" end) +
    "---\n"
  ' "$INPUT"
done

# Unverified Suspicions
unv_count=$(jq -r '.unverified_suspicions | length' "$INPUT")
if [[ "$unv_count" -gt 0 ]]; then
  echo "## 🔍 Unverified Suspicions ($unv_count)"
  echo ""
  echo "_These findings did not pass the verification pass. Not blocking, but worth investigating._"
  echo ""
  jq -r '
    .unverified_suspicions[] |
    "- **\(.title)** at `\(.file):\(.line_start)` — \(.description) " +
    "_(rejected by verify: \(.verify_reasoning // "no reasoning provided"))_"
  ' "$INPUT"
  echo ""
fi

echo "---"
echo ""
echo "_Generated by the \`pr-review\` skill (multi-agent fan-out + verify)._"
