git:
  pagers:
    - pager: delta --paging=never --syntax-theme='tokyonight_night'
      useConfig: false
gui:
  nerdFontsVersion: "3"
  showFileIcons: true
  theme:
    activeBorderColor:
      - "#00fbfb"
      - bold
    inactiveBorderColor:
      - "#707584"
    optionsTextColor:
      - "#7bafff"
    selectedLineBgColor:
      - "#172030"
    cherryPickedCommitBgColor:
      - "#ff79c6"
    cherryPickedCommitFgColor:
      - "#7bafff"
    unstagedChangesColor:
      - "#ff716c"
    defaultFgColor:
      - "#e0e5f6"
    searchingActiveBorderColor:
      - "#ffd866"
  authorColors:
    "*": "#00d9d9"
